name: CI Pipeline

on:
  push:
    paths:
      - 'project/**'
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Install python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.11.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Test env vars for python
        run: python -c 'import os;print(os.environ)'
        env:
          GENESIS_USERNAME: ${{ secrets.GENESIS_USERNAME }} 
          GENESIS_PASSWORD: ${{ secrets.GENESIS_PASSWORD }} 

      - name: Run tests
        run: |
          chmod +x ./project/tests.sh
          sh ./project/tests.sh
        env:
          GENESIS_USERNAME: ${{ secrets.GENESIS_USERNAME}}
          GENESIS_PASSWORD: ${{ secrets.GENESIS_PASSWORD}}
